<%@ Page Language="VB" AutoEventWireup="false" CodeFile="RenkoMacdDivergence.aspx.vb" Inherits="Rpchost.RenkoMacdDivergence" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
   <title>Forex Videos | Forex movies | Bollinger Band </title>
		<META NAME="AREA" CONTENT="Forex Finance">
		<META HTTP-EQUIV="AUDIENCE" CONTENT="General">
		<META NAME="SUBJECT" CONTENT="Forex Signals, forecasts and analysis">
		<META NAME="PLACENAME" CONTENT="Forex Traders Heaven">
		<META NAME="CREATOR" CONTENT="Rpchost.com">
		<META HTTP-EQUIV="Content-language" CONTENT="en-US">
		<META NAME="COPYRIGHT" CONTENT="Rpchost.com">
		<META NAME="DESCRIPTION" CONTENT="Forex videos training and free FX movies showing different strategies">
		<META NAME="KEYWORDS" CONTENT="forex videos, movies, training">
		<META NAME="ABSTRACT" CONTENT="The best forex signals online - Rpchost.com provides real time free forex signals, technical and fundamental signals, the best online resource for forex traders.">
		<META name="robots" content="index, follow">
		<META NAME="AUTHOR" CONTENT="Rpchost.com">
		<LINK rel="stylesheet" type="text/css" href="../StyleSheet.css">
		
</head>
<body>
    <form id="form1" runat="server">
    
    <table width="100%" cellspacing="0" cellpadding="0" border="0">
													<tr>
														<td class="INPUTBUTTON">
															&nbsp;<H8><asp:Label ID="lblTitle" runat="server" ></asp:Label></H8>
														</td>
													</tr>
													<tr>
														<td height="5"></td>
													</tr>
													<tr>
														<td class="BlackSmallText9" valign="top">
															<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
															
																<TR>
																	<td width="2"></td>
																	<TD valign=top class="BlackSmallText9"  height=10>
																		
																	</td>
																</TR>
																<TR>
																	<td width="2"></td>
																	<TD valign=top class="BlackSmallText9">
																		
                                                                        &nbsp;&nbsp;&nbsp;<asp:Label ID="lblHead" runat="server" CssClass="BlackTextBold" Text=""></asp:Label>
																	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
																	
																	
                                                                        <asp:HyperLink ID="HyperLink1" runat="server" ToolTip="Forex training video strategy"></asp:HyperLink>
																	</td>
																</TR>
																
																<TR>
																	<td width="2"></td>
																	<TD valign=top class="BlackSmallText9">   
																		
																	</td>
																</TR>
																
																<TR>
																	<td width="2"></td>
																	<TD valign=top class="BlackSmallText9" >
																		
																		<table>
																		<tr>
																		    <td valign=top> &nbsp;&nbsp;&nbsp;<asp:Label ID="lblEmbed" runat="server" Text=""></asp:Label></td>
																		    <td valign=top>&nbsp;&nbsp;&nbsp;<asp:Label ID="lblDesc" runat="server" CssClass="BlackTextBold" Text=""></asp:Label></td>
																		    <td></td>
																		</tr>
																		</table>
																		
																	</td>
																	<TD valign=top class="BlackSmallText9">
																	
																	</td>
																</TR>
																<TR>
																	<td width="2"></td>
																	<TD valign=top class="BlackSmallText9"  height=20>
																		
																	</td>
																</TR>
																<TR>
																	<td width="2"></td>
																	<TD valign=top class="BlackSmallText9" >
																		
																	</td>
																</TR>
																
																
																
														<TR>
																	<td width="2"></td>
																	<TD valign=top>
																		<hr />
																	</td>
																</TR>
																
																
																
																<TR>
																	<td width="2"></td>
																	<TD valign=top height=10>
																		
																	</td>
																</TR>
																
																<TR>
																	<td width="2"></td>
																	<TD valign=top height=10 >
																		<span class="BlueText">Signals generated by the EA of this strategy running on my MT4 live account</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class=RednormalText>[Refresh the page to get the latest signals]</span>
																		<br><br>
																	</td>
																	<td width="2"></td>
																</TR>
																															
																
																
																<TR>
																	<td width="2"></td>
																	
																	<TD  colspan=2>
																		
                                                                             <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="OrderID"  
                                                                            runat="server"
                                                                            Font-Size="X-Small" Font-Names="Verdana" ShowFooter="True" CellPadding="4"
                                                                            BorderWidth="1px" BorderStyle="None" BorderColor="#CC9966" 
                                                                            Width="100%" BackColor="White"
                                                                            Height="1px">

                                                                            <RowStyle  CssClass="BlackSmallText8"/>							
                                                                            <HeaderStyle Font-Bold="True" ForeColor="#FFFFCC" BackColor="#990000"></HeaderStyle>

                                                                            <Columns>
                                                                            <asp:BoundField DataField="OrderID" HeaderText="OrderID" InsertVisible="False" 
                                                                            ReadOnly="True" SortExpression="OrderID" HeaderStyle-Font-Size =7 HeaderStyle-Width ="10px" HeaderStyle-Height=1 />

                                                                            <asp:BoundField DataField="Signal" HeaderText="Signal" SortExpression="Signal" HeaderStyle-Font-Size =7 ControlStyle-Font-Size=6 FooterStyle-Font-Size=5 HeaderStyle-Width ="230px" HeaderStyle-Height=1/>
                                                                            <asp:BoundField DataField="Status" HeaderText="Status" 
                                                                            SortExpression="Status" HeaderStyle-Font-Size =7 HeaderStyle-Width ="10px" HeaderStyle-Height=1/>
                                                                            <asp:BoundField DataField="dtDateSignal" HeaderText="DateOpen" 
                                                                            SortExpression="dtDateSignal" HeaderStyle-Font-Size =7 
                                                                            HeaderStyle-Width ="100px" HeaderStyle-Height=1/>

                                                                            <asp:BoundField DataField="dtDateClose" HeaderText="DateClose" 
                                                                            SortExpression="dtDateClose" HeaderStyle-Font-Size =7 
                                                                            HeaderStyle-Width ="100px" HeaderStyle-Height=1/>

                                                                            <asp:BoundField DataField="Entry" HeaderText="Entry" SortExpression="Entry" HeaderStyle-Font-Size =7 HeaderStyle-Width ="10px" HeaderStyle-Height=1/>
                                                                            <asp:BoundField DataField="SL" HeaderText="SL" SortExpression="SL" HeaderStyle-Font-Size =7 HeaderStyle-Width ="10px" HeaderStyle-Height=1/>
                                                                            <asp:BoundField DataField="Target" HeaderText="Target" 
                                                                            SortExpression="Target" HeaderStyle-Font-Size =7 HeaderStyle-Width ="10px" HeaderStyle-Height=1/>

                                                                            <asp:BoundField DataField="Profit" HeaderText="Profit(in $)" 
                                                                            SortExpression="Profit" HeaderStyle-Font-Size =7 HeaderStyle-Width ="10px" HeaderStyle-Height=1/>

                                                                            </Columns>
                                                                            </asp:GridView>
																		
																		
																	</td>
																	
																	<td width="2"></td>
																</TR>
																
																
							
																
																
															</TABLE>
														</td>
													</tr>
													
														<tr>
													<td height=20>
													</td>
													<td >
													</td>
													</tr>
													
													<tr>
													<td >
													
													<table>
													   
													    <tr>
													    <td valign=top> 
													    
													     <table>
													     <tr>
													    <td valign=top width=10> 
													    
													       <!-- admitad.banner: 7u2tphpueg2504a66eeb22af2ed61b GearBest.com INT -->
<a target="_blank" rel="nofollow" href="https://lenkmio.com/g/7u2tphpueg2504a66eeb22af2ed61b/?i=4"><img width="250" height="250" border="0" src="https://ad.admitad.com/b/7u2tphpueg2504a66eeb22af2ed61b/" alt="GearBest.com INT"/></a>
<!-- /admitad.banner -->
													        </td>
													    <td valign=top>
													     <!-- admitad.banner: citnn5gkqd2504a66eeb3d619ec8d1 Trends Brands -->
<a target="_blank" rel="nofollow" href="https://ad.admitad.com/g/citnn5gkqd2504a66eeb3d619ec8d1/?i=4"><img width="250" height="250" border="0" src="https://ad.admitad.com/b/citnn5gkqd2504a66eeb3d619ec8d1/" alt="Trends Brands"/></a>
<!-- /admitad.banner -->
													    
													     </td>
													     
													     
													      <td valign=top>
													     <script type='text/javascript'>													         (function() {
													             /* Optional settings (these lines can be removed): */
													             subID = "";  // - local banner key;
													             injectTo = "";  // - #id of html element (ex., "top-banner").
													             /* End settings block */

													             if (injectTo == "") injectTo = "admitad_shuffle" + subID + Math.round(Math.random() * 100000000);
													             if (subID == '') subid_block = ''; else subid_block = 'subid/' + subID + '/';
													             document.write('<div id="' + injectTo + '"></div>');
													             var s = document.createElement('script');
													             s.type = 'text/javascript'; s.async = true;
													             s.src = 'https://ad.admitad.com/shuffle/11b5545f3a/' + subid_block + '?inject_to=' + injectTo;
													             var x = document.getElementsByTagName('script')[0];
													             x.parentNode.insertBefore(s, x);
													         })();</script>
													    
													     </td>
													      <td valign=top>
													     <!-- admitad.banner: xxbpg7wf8y2504a66eeb1a479c6d7c ТРАЕКТОРИЯ -->
<a target="_blank" rel="nofollow" href="https://ad.admitad.com/g/xxbpg7wf8y2504a66eeb1a479c6d7c/?i=4"><img width="200" height="200" border="0" src="https://ad.admitad.com/b/xxbpg7wf8y2504a66eeb1a479c6d7c/" alt="ТРАЕКТОРИЯ"/></a>
<!-- /admitad.banner -->
													    
													     </td>
													     
													     
													      <td valign=top>
													    <!-- admitad.banner: n1ghvj543b2504a66eebf177fa6ee8 alibaba.com TR -->
<a target="_blank" rel="nofollow" href="https://alibabato.com/g/n1ghvj543b2504a66eebf177fa6ee8/?i=4"><img width="250" height="250" border="0" src="https://ad.admitad.com/b/n1ghvj543b2504a66eebf177fa6ee8/" alt="alibaba.com TR"/></a>
<!-- /admitad.banner -->
													    
													     </td>
													     
													     
													      <td valign=top>
										
													    
<a target="_blank" rel="nofollow" href="https://alitems.com/g/1f613e272f2504a66eeb16525dc3e8/?i=4"><img width="125" height="125" border="0" src="https://alitems.com/b/1f613e272f2504a66eeb16525dc3e8/" alt="Aliexpress INT"/></a></td>
													     
													     </tr>
													     
													     
													     
													     
													     
													     <tr>
													    <td valign=top> 
													     
													     <!-- admitad.banner: 1f613e272f2504a66eeb16525dc3e8 Aliexpress INT -->
&nbsp;<!-- /admitad.banner --><a target="_blank" rel="nofollow" href="https://ad.admitad.com/g/54bujq4qhp2504a66eeb038bd26e14/?i=4"><img width="250" height="250" border="0" src="https://ad.admitad.com/b/54bujq4qhp2504a66eeb038bd26e14/" alt="SENSEIT"/></a></td>
													    <td valign=top>
													    <!-- admitad.banner: 54bujq4qhp2504a66eeb038bd26e14 SENSEIT -->
&nbsp;<!-- /admitad.banner --></td>
													     
													     
													      <td valign=top>
													    
													    
													     </td>
													      <td valign=top>
													    
													    
													     </td>
													     
													     
													      <td valign=top>
													    
													    
													     </td>
													     
													     
													      <td valign=top>
										
													    
													     </td>
													     
													     </tr>
													     
													     
													     
													    
													   
													   
													</table>
													
												    
                                                    </td>
													
													</tr>
												</table>
												<!-- End Content -->
												



	




    </form>
</body>
</html>
